package constants

const (
	ConfigName          = "Config"
	LoggerName          = "Logger"
	PgSQLConnectionName = "PgSQL"
	RedisName           = "Redis"
	HTTPServerName      = "HTTPServer"
	QueueName           = "Queue"
	ValidatorName       = "Validator"
	AuthorizerName      = "Authorizer"
	TOTPName            = "TOTP"
	MailgunName         = "Mailgun"
	RPCName             = "RPC"
	TracerName          = "Tracer"
	HistoryName         = "History"
	OverlordClientName  = "OverlordClient"

	AuthenticationServiceName  = "AuthenticateService"
	AuthorizationServiceName   = "AuthorizationService"
	AccountServiceName         = "AccountService"
	SessionServiceName         = "SessionService"
	OrganizationServiceName    = "OrganizationService"
	GameServiceName            = "GameService"
	SpinServiceName            = "SpinService"
	CurrencyServiceName        = "CurrencyService"
	MailingServiceName         = "MailingService"
	WagerSetServiceName        = "WagerSetService"
	CurrencySetServiceName     = "CurrencySetService"
	ConfigSenderServiceName    = "ConfigSenderService"
	DebugServiceName           = "DebugService"
	FileDownloadingServiceName = "FileDownloadingService"
	LobbyServiceName           = "LobbyService"
	ClientInfoServiceName      = "ClientInfoService"

	AccountRepositoryName      = "AccountRepository"
	SessionRepositoryName      = "SessionRepository"
	FileRepositoryName         = "FileRepository"
	RefreshTokenRepositoryName = "RefreshTokenRepository"
	RoleRepositoryName         = "RoleRepository"
	PermissionRepositoryName   = "PermissionRepository"
	GameRepositoryName         = "GameRepository"
	OrganizationRepositoryName = "OrganizationRepository"
	CurrencyRepositoryName     = "CurrencyRepository"
	WagerSetRepositoryName     = "WagerSetRepository"
	CurrencySetRepositoryName  = "CurrencySetRepository"
	DebugRepositoryName        = "DebugRepository"

	MetaHTTPHandlerName         = "MetaHTTPHandler"
	AuthHTTPHandlerName         = "AuthHTTPHandler"
	DashboardHTTPHandlerName    = "DashboardHTTPHandler"
	AccountHTTPHandlerName      = "AccountHTTPHandler"
	RoleHTTPHandlerName         = "RoleHTTPHandler"
	PermissionHTTPHandlerName   = "PermissionHTTPHandler"
	GameHTTPHandlerName         = "GameHTTPHandler"
	ReportHTTPHandlerName       = "ReportHTTPHandler"
	OrganizationHTTPHandlerName = "OrganizationHTTPHandler"
	DictionaryHTTPHandlerName   = "DictionaryHTTPHandler"
	CurrencyHTTPHandlerName     = "CurrencyHTTPHandler"
	WagerSetHTTPHandlerName     = "WagerSetHTTPHandler"
	CurrencySetHTTPHandlerName  = "CurrencySetHTTPHandler"
	FileSetHTTPHandlerName      = "FileSetHTTPHandler"

	CurrencyQueueHandlerName    = "CurrencyQueueHandler"
	PublicReportHTTPHandlerName = "PublicReportHTTPHandler"
	LobbyHTTPHandlerName        = "LobbyHTTPHandler"
	ClientInfoHTTPHandlerName   = "ClientInfoHTTPHandler"

	ExchangeName = "Exchange"
)
